// Hero roster — compiled from public game knowledge, current as of Patch 2.1.95 (Aug 2026)
// roles: tank, fighter, assassin, mage, marksman, support
// lane: exp, jungle, mid, gold, roam
// tier: 'S' | 'A' | null  (rough current-patch meta flag, optional, editable)
// tag: short badge text, e.g. 'NEW', 'REWORK'

const HEROES = [
  // ---- TANK ----
  { name: "Tigreal", roles: ["tank"], lane: ["roam"] },
  { name: "Franco", roles: ["tank"], lane: ["roam"] },
  { name: "Akai", roles: ["tank"], lane: ["roam", "jungle"] },
  { name: "Minotaur", roles: ["tank"], lane: ["roam"], tier: "S" },
  { name: "Johnson", roles: ["tank"], lane: ["roam"] },
  { name: "Uranus", roles: ["tank"], lane: ["exp"] },
  { name: "Gatotkaca", roles: ["tank", "fighter"], lane: ["roam"] },
  { name: "Grock", roles: ["tank", "fighter"], lane: ["exp"] },
  { name: "Belerick", roles: ["tank"], lane: ["roam"] },
  { name: "Khufra", roles: ["tank"], lane: ["roam"], tier: "S" },
  { name: "Baxia", roles: ["tank"], lane: ["jungle", "roam"] },
  { name: "Barats", roles: ["tank"], lane: ["roam"] },
  { name: "Atlas", roles: ["tank", "support"], lane: ["roam"] },
  { name: "Hylos", roles: ["tank"], lane: ["roam"] },
  { name: "Edith", roles: ["tank", "marksman"], lane: ["roam"] },
  { name: "Gloo", roles: ["tank"], lane: ["exp", "roam"], tier: "S" },
  { name: "Fredrinn", roles: ["fighter", "tank"], lane: ["jungle", "exp"] },
  { name: "Chip", roles: ["tank"], lane: ["roam"] },

  // ---- FIGHTER ----
  { name: "Balmond", roles: ["fighter"], lane: ["jungle"] },
  { name: "Alucard", roles: ["fighter"], lane: ["jungle"] },
  { name: "Bane", roles: ["fighter", "mage"], lane: ["exp"] },
  { name: "Zilong", roles: ["fighter"], lane: ["jungle"] },
  { name: "Freya", roles: ["fighter"], lane: ["exp"] },
  { name: "Aldous", roles: ["fighter"], lane: ["jungle"] },
  { name: "Chou", roles: ["fighter", "assassin"], lane: ["exp", "roam"] },
  { name: "Sun", roles: ["fighter"], lane: ["jungle"] },
  { name: "Alpha", roles: ["fighter"], lane: ["exp"] },
  { name: "Ruby", roles: ["fighter", "tank"], lane: ["jungle"] },
  { name: "Argus", roles: ["fighter"], lane: ["exp"] },
  { name: "Jawhead", roles: ["fighter"], lane: ["jungle", "exp"] },
  { name: "Lapu-Lapu", roles: ["fighter"], lane: ["exp"] },
  { name: "Yu Zhong", roles: ["fighter"], lane: ["exp"] },
  { name: "Thamuz", roles: ["fighter"], lane: ["exp"] },
  { name: "Minsitthar", roles: ["fighter"], lane: ["exp"] },
  { name: "Dyrroth", roles: ["fighter"], lane: ["exp"] },
  { name: "Silvanna", roles: ["fighter"], lane: ["exp"] },
  { name: "Guinevere", roles: ["fighter"], lane: ["jungle"] },
  { name: "Khaleed", roles: ["fighter"], lane: ["exp"] },
  { name: "Badang", roles: ["fighter"], lane: ["jungle", "exp"] },
  { name: "X.Borg", roles: ["fighter"], lane: ["exp"] },
  { name: "Terizla", roles: ["fighter"], lane: ["exp"] },
  { name: "Masha", roles: ["fighter"], lane: ["jungle"], tier: "S" },
  { name: "Yin", roles: ["fighter"], lane: ["jungle"] },
  { name: "Phoveus", roles: ["fighter"], lane: ["exp", "jungle"] },
  { name: "Martis", roles: ["fighter"], lane: ["jungle"] },
  { name: "Aulus", roles: ["fighter"], lane: ["exp"] },
  { name: "Paquito", roles: ["fighter"], lane: ["exp", "jungle"] },
  { name: "Arlott", roles: ["fighter"], lane: ["exp"] },
  { name: "Cici", roles: ["fighter"], lane: ["exp"] },
  { name: "Lukas", roles: ["fighter"], lane: ["jungle"] },
  { name: "Kaja", roles: ["fighter", "support"], lane: ["roam"], tag: "REWORK 2.1.95" },
  { name: "Zetian", roles: ["fighter", "mage"], lane: ["exp"] },

  // ---- ASSASSIN ----
  { name: "Saber", roles: ["assassin"], lane: ["jungle"] },
  { name: "Karina", roles: ["assassin"], lane: ["jungle"] },
  { name: "Fanny", roles: ["assassin"], lane: ["jungle"] },
  { name: "Hayabusa", roles: ["assassin"], lane: ["jungle"] },
  { name: "Natalia", roles: ["assassin"], lane: ["roam", "jungle"] },
  { name: "Helcurt", roles: ["assassin"], lane: ["jungle"] },
  { name: "Lancelot", roles: ["assassin"], lane: ["jungle"] },
  { name: "Ling", roles: ["assassin"], lane: ["jungle"] },
  { name: "Gusion", roles: ["assassin", "mage"], lane: ["jungle"] },
  { name: "Aamon", roles: ["assassin"], lane: ["jungle"] },
  { name: "Benedetta", roles: ["fighter", "assassin"], lane: ["exp", "jungle"] },
  { name: "Yi Sun-shin", roles: ["assassin", "marksman"], lane: ["jungle"] },
  { name: "Joy", roles: ["assassin"], lane: ["jungle"] },
  { name: "Harley", roles: ["mage", "assassin"], lane: ["mid", "jungle"] },
  { name: "Julian", roles: ["fighter", "assassin"], lane: ["exp"] },
  { name: "Suyou", roles: ["fighter", "assassin"], lane: ["exp", "jungle"] },
  { name: "Hanzo", roles: ["assassin"], lane: ["jungle"], tier: "S" },
  { name: "Hirara", roles: ["assassin"], lane: ["jungle"], tag: "NEW" },

  // ---- MAGE ----
  { name: "Nana", roles: ["mage"], lane: ["mid"] },
  { name: "Eudora", roles: ["mage"], lane: ["mid"] },
  { name: "Alice", roles: ["mage", "tank"], lane: ["mid", "jungle"] },
  { name: "Vexana", roles: ["mage"], lane: ["mid"] },
  { name: "Zhask", roles: ["mage"], lane: ["mid"] },
  { name: "Aurora", roles: ["mage"], lane: ["mid"] },
  { name: "Valir", roles: ["mage"], lane: ["mid"] },
  { name: "Odette", roles: ["mage"], lane: ["mid"] },
  { name: "Cyclops", roles: ["mage"], lane: ["mid"] },
  { name: "Kagura", roles: ["mage"], lane: ["mid"] },
  { name: "Chang'e", roles: ["mage"], lane: ["mid"] },
  { name: "Pharsa", roles: ["mage"], lane: ["mid"] },
  { name: "Kadita", roles: ["mage", "assassin"], lane: ["mid", "jungle"] },
  { name: "Lunox", roles: ["mage"], lane: ["mid"] },
  { name: "Harith", roles: ["mage"], lane: ["mid"] },
  { name: "Selena", roles: ["mage", "assassin"], lane: ["mid", "roam"] },
  { name: "Vale", roles: ["mage"], lane: ["mid"] },
  { name: "Luo Yi", roles: ["mage"], lane: ["mid"] },
  { name: "Cecilion", roles: ["mage"], lane: ["mid"] },
  { name: "Xavier", roles: ["mage"], lane: ["mid"] },
  { name: "Yve", roles: ["mage"], lane: ["mid"] },
  { name: "Novaria", roles: ["mage"], lane: ["mid"], tag: "BUFF 2.1.95" },
  { name: "Lylia", roles: ["mage"], lane: ["mid"] },
  { name: "Valentina", roles: ["mage"], lane: ["mid"] },
  { name: "Gord", roles: ["mage"], lane: ["mid"], tag: "NERF 2.1.95" },
  { name: "Esmeralda", roles: ["mage", "support"], lane: ["roam", "jungle"] },
  { name: "Sora", roles: ["mage"], lane: ["mid"] },
  { name: "Zhuxin", roles: ["mage", "tank"], lane: ["mid", "roam"] },

  // ---- MARKSMAN ----
  { name: "Miya", roles: ["marksman"], lane: ["gold"] },
  { name: "Bruno", roles: ["marksman"], lane: ["gold"], tag: "REVAMP" },
  { name: "Clint", roles: ["marksman"], lane: ["gold"] },
  { name: "Layla", roles: ["marksman"], lane: ["gold"] },
  { name: "Moskov", roles: ["marksman"], lane: ["gold"] },
  { name: "Karrie", roles: ["marksman"], lane: ["gold"] },
  { name: "Irithel", roles: ["marksman"], lane: ["gold"] },
  { name: "Hanabi", roles: ["marksman"], lane: ["gold"] },
  { name: "Granger", roles: ["marksman"], lane: ["gold"] },
  { name: "Claude", roles: ["marksman"], lane: ["gold"] },
  { name: "Kimmy", roles: ["marksman", "mage"], lane: ["gold"] },
  { name: "Lesley", roles: ["marksman"], lane: ["gold"] },
  { name: "Wanwan", roles: ["marksman"], lane: ["gold"] },
  { name: "Popol and Kupa", roles: ["marksman"], lane: ["gold"] },
  { name: "Brody", roles: ["marksman"], lane: ["gold"] },
  { name: "Beatrix", roles: ["marksman"], lane: ["gold"] },
  { name: "Natan", roles: ["marksman"], lane: ["gold"] },
  { name: "Melissa", roles: ["marksman"], lane: ["gold"], tier: "S" },
  { name: "Ixia", roles: ["marksman"], lane: ["gold"] },

  // ---- SUPPORT ----
  { name: "Estes", roles: ["support"], lane: ["roam"] },
  { name: "Rafaela", roles: ["support"], lane: ["roam"], tier: "S" },
  { name: "Angela", roles: ["support"], lane: ["roam"] },
  { name: "Diggie", roles: ["support"], lane: ["roam"] },
  { name: "Floryn", roles: ["support"], lane: ["roam"] },
  { name: "Mathilda", roles: ["support", "assassin"], lane: ["roam", "jungle"] },
  { name: "Carmilla", roles: ["support"], lane: ["roam"] },
  { name: "Lolita", roles: ["support", "tank"], lane: ["roam"] },
  { name: "Faramis", roles: ["support", "mage"], lane: ["roam"] },
  { name: "Marcel", roles: ["support"], lane: ["roam"], tag: "NEW" },
];

// Small set of well-known hard-counter relationships used to power live
// suggestions. Not exhaustive — meant as directional signal, not gospel.
const COUNTERS = {
  "Fanny": ["Helcurt", "Selena", "Ling"],
  "Hayabusa": ["Helcurt", "Ling", "Kadita"],
  "Ling": ["Helcurt", "Selena", "Khufra"],
  "Lancelot": ["Helcurt", "Ruby", "Franco"],
  "Gusion": ["Khufra", "Franco", "Minotaur"],
  "Harith": ["Khufra", "Franco", "Lancelot"],
  "Claude": ["Franco", "Khufra", "Helcurt"],
  "Wanwan": ["Khufra", "Franco", "Helcurt"],
  "Karrie": ["Franco", "Khufra", "Minotaur"],
  "Granger": ["Franco", "Khufra", "Helcurt"],
  "Kaja": ["Angela", "Diggie", "Karina"],
  "Chou": ["Franco", "Khufra", "Uranus"],
  "Freya": ["Khufra", "Franco", "Uranus"],
  "Yu Zhong": ["Khufra", "Chou", "Ruby"],
  "Esmeralda": ["Gusion", "Lesley", "Karrie"],
  "Uranus": ["Gusion", "Karina", "Lesley"],
  "Alucard": ["Khufra", "Ling", "Franco"],
};
